// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVC_Shekru_WebApplication.Models;

public partial class Designation
{
    public int DesignationIdRef { get; set; }

    public string DesignationName { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<DesignationGrade> DesignationGrades { get; set; } = new List<DesignationGrade>();

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}