// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MVC_Shekru_WebApplication.Models;

public partial class MVC_ShekruContext : DbContext
{
    public MVC_ShekruContext(DbContextOptions<MVC_ShekruContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Designation> Designations { get; set; }

    public virtual DbSet<DesignationGrade> DesignationGrades { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Designation>(entity =>
        {
            entity.HasKey(e => e.DesignationIdRef).HasName("PK__Designat__DB8FF87A03904C02");

            entity.ToTable("Designation");

            entity.Property(e => e.DesignationIdRef).ValueGeneratedNever();
            entity.Property(e => e.DesignationName).HasMaxLength(100);
        });

        modelBuilder.Entity<DesignationGrade>(entity =>
        {
            entity.HasKey(e => e.GradeIdRef).HasName("PK__Designat__D91BD1F33626805C");

            entity.ToTable("DesignationGrade");

            entity.Property(e => e.GradeIdRef).ValueGeneratedNever();
            entity.Property(e => e.GradeName).HasMaxLength(100);

            entity.HasOne(d => d.DesignationIdRefNavigation).WithMany(p => p.DesignationGrades)
                .HasForeignKey(d => d.DesignationIdRef)
                .HasConstraintName("FK__Designati__Desig__4BAC3F29");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3214EC076489E8D2");

            entity.ToTable("Employee");

            entity.HasIndex(e => e.EmailAddress, "UQ__Employee__49A14740D2DD3125").IsUnique();

            entity.Property(e => e.EmailAddress).HasMaxLength(100);
            entity.Property(e => e.Firstname).HasMaxLength(100);
            entity.Property(e => e.Lastname).HasMaxLength(100);
            entity.Property(e => e.Phonenumber).HasMaxLength(12);

            entity.HasOne(d => d.DesignationIdRefNavigation).WithMany(p => p.Employees)
                .HasForeignKey(d => d.DesignationIdRef)
                .HasConstraintName("FK__Employee__Design__5070F446");

            entity.HasOne(d => d.GradeIdRefNavigation).WithMany(p => p.Employees)
                .HasForeignKey(d => d.GradeIdRef)
                .HasConstraintName("FK__Employee__GradeI__5165187F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}